#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  # TODO: move to a test build that can reuse the artifacts from the duckdb _extension_distribution workflow
  minio-testing:
    name: Run tests with Minio
    uses: ./.github/workflows/_minio_testing.yml
    with:
      duckdb_version: v0.10.0

  duckdb-stable-build:
    name: Build extension binaries
#    needs: minio-testing
    uses: duckdb/duckdb/.github/workflows/_extension_distribution.yml@v0.10.0
    with:
      duckdb_version: v0.10.0
      extension_name: httpfs
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/duckdb/.github/workflows/_extension_deploy.yml@v0.10.0
    secrets: inherit
    with:
      duckdb_version: v0.10.0
      extension_name: httpfs
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
      deploy_versioned: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}